### ISSUE TITLE
Entity name should be always singular

### ISSUE THREAD

**Issue by meheedihasaan** [iamkhs/Notes-Venture#2]
Use singular form as an entity name. You can use plural form as a table name. To define table name use the following annotation in entity level - 

`@Table(name = "table_name")`

Here 'table_name' will be replaced by your actual table name.

Also, use the singular form as Service and Repository name. Fot example - NoteRepository.java, NoteService.java.

For more - https://www.baeldung.com/spring-data-jpa-custom-naming

**Comment by iamkhs** [comment]
fixed.
